# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mi-app-gitops-svc
  namespace: mi-super-app
spec:
  type: NodePort
  selector:
    app: mi-app-gitops
  ports:
  - port: 8080
    targetPort: 8080
